version: "3.0"

services:

  api:
    build: .
      context: .
    image: untar-demo
    ports:
      - 3000:3000
    volumes:
      - ./services/:/app/services/
    env_file: docker-compose.env
    environment:
      SERVICEDIR: services
      PORT: 3000
    links:
      - nats
    depends_on:
      - nats

  nats:
    image: nats
